name: kata
version: 0.0.1
description: App for Kata04 Exercise
author: John Evans <prujohn@gmail.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  kata_util:
      path: ../chemaxon_util
  args: "^0.13.2"
  logging: "^0.11.2"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
